### ISSUE TITLE
QuantizeScale not RenderableScale?

### ISSUE THREAD

**Issue by ericgj** [gampleman/elm-visualization#5]
I get an error calling Axis.axis with a QuantizeScale.  It looks like the types don't line up for  `ticks` and `tickFormat` . Am I missing something?

## QuantizeScale a
```elm
{ domain : (Float, Float)
, range : (a, List a)
, convert : (Float, Float) -> (a, List a) -> Float -> a
, invertExtent : (Float, Float) -> (a, List a) -> a -> Maybe (Float, Float)
, ticks : (Float, Float) -> (a, List a) -> Int -> List Float
, tickFormat : (Float, Float) -> (a, List a) -> Int -> Float -> String
, nice : (Float, Float) -> Int -> (Float, Float)
, rangeExtent : (Float, Float) -> (a, List a) -> (a, a) 
}
```

## RenderableScale
```elm
{ a | 
    ticks : domain -> Int -> List value
  , domain : domain
  , tickFormat : domain -> Int -> value -> String
  , convert : domain -> range -> value -> Float
  , range : range
  , rangeExtent : domain -> range -> (Float, Float) 
}
```

**Comment by gampleman** [comment]
Looks like a bug (unfortunately, this might be a breaking change if the types need changing). The scales still need quite a bit of fleshing out. Only the convert method is really done on the quantize scale, the others are placeholders only (see https://github.com/gampleman/elm-visualization/blob/master/src/Visualization/Scale/Quantize.elm#L88). 

I must have released the quantize scale by accident, it shouldn't have been made public yet, as it's not done. My apologies for the confusion.

**Comment by gampleman** [comment]
I have fixed this in a PR (#6), but it is a major breaking change, so would prefer to delay releasing (unless you have an urgent need?). In the meantime I've released a patch-level release that clarifies the docs that this is currently not supported.

**Comment by ericgj** [comment]
Not urgent at all, thanks for the clarification!  Rather have it done right than rush anything.  Still not sure if I understand how/when to use quantize scales but I will puzzle around some more between the code and d3's dense documentation :)

Thanks very much for this library by the way, it's really very useful even incomplete as it is. I did a little [interactive line plot example](https://ellie-app.com/35MRYtkBW3da1/12), if you are interested I could package it up for the examples in this repo.
